config/routes.rb
DrawSystem::Application.routes.draw do
  resources :clubs

end

app/models/club.rb
class Club < ActiveRecord::Base
  # ================
  # = Associations =
  # ================
  belongs_to :country
  belongs_to :region
  has_many :sheets

  # ===============
  # = Validations =
  # ===============
  validates :name, :presence => true
end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/models/region.rb
class Region < ActiveRecord::Base
  # ================
  # = Associations =
  # ================
  has_many :clubs
  
  # ================
  # = Vallidations =
  # ================
  validates :name, :presence => true
end

app/models/sheet.rb
class Sheet < ActiveRecord::Base
  
  # ================
  # = Associations =
  # ================
  belongs_to :club
  
  # ===============
  # = Validations =
  # =============== 
  validates :number, :numericality => { :only_integer => true, :greater_than => 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  
  def index
    @clubs = Club.order(:name)
  end
  
  def show
  end
  
  def new
  end
  
  def edit
  end
  
  def create
  end
  
  def update
  end
  
  def destroy
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/views/clubs/_club.html.haml
%tr
  %td= link_to(club.name, club_path(club))
  %td
    = [club.city, club.province].compact.join(", ")
  %td= club.region.try(:name)
  %td= club.website
  %td= club.sheets.count
  %td= link_to(image_tag('link_icons/magnifier.png', :title => 'View'), club_path(club))
    

app/views/clubs/index.html.haml
- @header = 'CurlManitoba Member Clubs'

%table.bordered-table.zebra-striped
  %thead
    %tr
      %th Name
      %th City/Province
      %th Region
      %th Website
      %th Sheets
      %th
  %tbody
    - if @clubs.size > 0
      = render @clubs
    - else
      %tr
        %td{:colspan => 5}
          No Clubs Available

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title CurlManitoba - Draw Planner
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tag
    = yield :js
  %body

    %section#navigation
      .topbar-wrapper{:style => "z-index: 5;"}
        .topbar{:style => 'position: relative'}
          .fill
            .container
              %h3
                %a{:href => "/"} MCA Bonspiel
          / /fill
        / /topbar

    .container

      .content
        .page-header
          %h1= @header
      
        = yield

      %footer
        &copy; 2012

    #dialog_container
      = yield :dialogs